#!/bin/sh
# Base Section

# Extra Section
# Copyleft, AOSC Developers.

# Purpose of this section:
# 1. Adjustment for current system.
# 2. News and issues to be read and advised by the users.

mknod -m 600 /dev/console c 5 1 2>/dev/null || true
mknod -m 666 /dev/null c 1 3 2>/dev/null || true

# Transition to new independent tmp for systemd PrivateTemp.
rm -rf /var/tmp
install -dm1777 /var/tmp

echo -e "\

Welcome to AOSC OS (4.0.1)!

This is a bugfix release over Core 4.0.0:

- Adds extra PATH for Perl site and vendor directories (#39);
- Misc. fixes for MIPS32 (mipsel);

--------------------------------------------------------------------------------

For a full changelog of Core 4.0.0, please read at:

  https://github.com/AOSC-Dev/aosc-os-core/releases/tag/v4.0.0

--------------------------------------------------------------------------------

For any questions encountered, please report at:

  https://github.com/AOSC-Dev/aosc-os-core/issues
"

if [[ ! -e /etc/fstab ]]; then
cat > /etc/fstab << EOF
# /etc/fstab
#
# <device>: the block device to be mounted.
# <mntpnt>: mount point, the mounting destination of the block device.
# <fstyte>: file system type, e.g. ext4, btrfs, etc.
# <options>: extra options to be passed to the file system driver.
# <dump>: whether the dump utility should dump and backup this particular
#         device/filesystem. Takes one of the following numeric values:
#         0 - ignore this device/filesystem;
#         1 - make a backup for this device/filesystem;
# <pass>: in what order fsck should do a file system check on this particular
#         device/filesystem. Takes one of the following numeric values:
#         0 - ignore this device/filesystem (btrfs should use 0);
#         1/2 - given a file system check is necessary, the order in which
#               the checks should proceed.
#
# <device>	<mntpnt>	<fstype>	<options>	<dump>	<pass>
EOF
fi
