#!/bin/sh
#
# Base Section
#

#
# Extra Section
#
# Copyleft, AOSC Developers.
#
# Purpose of this section:
# 1. Adjustment for current system.
# 2. News and issues to be read and advised by the users.
#

mknod -m 600 /dev/console c 5 1 || true
mknod -m 666 /dev/null c 1 3 || true

printf "\

Welcome to AOSC OS (with the brand new Core 3.4.1)!

Core 3.4.1 is a maintenance update for AOSC OS Core.

	- Fixes some build-time issues with GCC (PR69140).

For any issue encountered in the future, please report them as an Issue at

https://github.com/AOSC-Dev/aosc-os-core/issues/

"
